---

- name: config - create group
  group:
    name={{ vulture_group }}
    system=yes

- name: config - create user
  user:
    name={{ vulture_user }}
    group={{ vulture_group }}
    system=yes
    createhome=no

- name: config - create config dir
  file:
    state=directory
    path={{ vulture_config_dir }}
    mode=755
    owner={{ vulture_user }}
    group={{ vulture_group }}

- name: config - create log dir
  file:
    state=directory
    path={{ vulture_log_dir }}
    mode=0755
    owner={{ vulture_user }}
    group={{ vulture_group }}

- name: config - logconf
  template:
    src=logconf.xml.j2
    dest={{ vulture_config_dir }}/logconf.xml
    owner={{ vulture_user }}
    group={{ vulture_group }}
  notify: restart vulture

- name: config - config.json
  template:
    src=config.json.j2
    dest={{ vulture_config_dir }}/config.json
  notify: restart vulture

