---

- name: service - setup and run
  runit:
    name: "{{ vulture_service_name }}"
    enabled: yes
    state: up
    timeout: 10
    user: "{{ vulture_user }}"
    command: "{{vulture_install_dir}}/vulture/vulture -config {{ vulture_config_dir }}/config.json"
    env_vars:
      GOMAXPROCS: "{{ansible_processor_cores + 1}}"
  register: vulture_service_status

